api_server=https://api.dandanplay.net
auto_load=no
autoload_for_url=yes
autoload_local_danmaku=no
save_danmaku=no
merge_tolerance=0
max_screen_danmaku=0
chConvert=0
scrolltime=10
fixtime=5
vf_fps=yes
opacity=0.55
fontname=SimHei
fontsize=16
bold=yes
outline=1
shadow=0
displayarea=0.05
history_path=~~/_cache/danmaku-history.json
